package com.company.crm.ws.sso;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2018-08-26T22:00:46.791+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebServiceClient(name = "ISSOServiceService", 
                  wsdlLocation = "http://www.server.com/ws/SSOService?wsdl",
                  targetNamespace = "http://sso.ws.crm.company.com/") 
public class ISSOServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sso.ws.crm.company.com/", "ISSOServiceService");
    public final static QName ISSOServicePort = new QName("http://sso.ws.crm.company.com/", "ISSOServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.server.com/ws/SSOService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISSOServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.server.com/ws/SSOService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISSOServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISSOServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISSOServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISSOServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISSOServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISSOServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ISSOService
     */
    @WebEndpoint(name = "ISSOServicePort")
    public ISSOService getISSOServicePort() {
        return super.getPort(ISSOServicePort, ISSOService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISSOService
     */
    @WebEndpoint(name = "ISSOServicePort")
    public ISSOService getISSOServicePort(WebServiceFeature... features) {
        return super.getPort(ISSOServicePort, ISSOService.class, features);
    }

}
